### ISSUE TITLE
Epic 5: Tree Details Page with functional builds, boots and tests

### ISSUE THREAD

**Issue by joaobertacchi** [kernelci/dashboard#126]
**Sprint Goal**: navigate to Tree Listing page Tree Details page and show case all the features. Focus on lists of builds, boots and tests and respective details page.

- [x] show the health of the tree using the history graph (p1)
- [x] revert to tree (pay attention to tree header) (p2)
- [x] executions list for boots (p3)
- [x] navigate to the past using the graph. HEAD is highlighted. (p4)
- [ ] show commit message in history (p4)
- [ ] send feedback through email (not required for plumbers, but important)
