### ISSUE TITLE
Epic 6: Tree Details Page with functional builds, boots and tests

### ISSUE THREAD

**Issue by joaobertacchi** [kernelci/dashboard#219]
**Sprint Goal**: navigate to Tree Listing page Tree Details page and show case all the features. Focus on lists of builds, boots and tests and respective details page.
Demo: user uses dashboard to investigate problems with a tree. Dashboard is used to easily grasp build, boot and test errors. Tree Details Page is used for filtering data and identifying the root cause.

**History Chart**
- [x] #151  (p1)
- [ ] ~show commit message (p2)~

**Status Changes**
- [x] make sure all stats match (builds, boots, tests) (p1): #159 , #203 
- [x] #232
- [x] #233
- [x] #249
- [x] #250
- [x] #251
- [x] #252
- [x] #253
- [x] #286

**Tree Listing Page**
- [x] #263
- [x] #265
- [x] #227
- [x] #225
- [x] #226
- [x] #224
- [x] #228

**Tree Details Page**
- [x] #260
- [ ] #264
- [x] #259
- [ ] #229
- [ ] #222
- [ ] #230

**Test Details Page**
- [x] #261

**Left Menu**
- [x] #94 
- [x] #223

**Comment by joaobertacchi** [comment]
Comments from @padovan:
- Add datetime (on hover) on the history graph
- git describe seems to be missing on the per build pages, not sure if that's just the data not going into the database or not.
- tree view: commit/tag should be wider
- tree view:  Build status should be pass/fail, not valid/invalid.
- tree view: git url could be trimmed
- history graph: Success/fail instead of valid/invalid

**Comment by joaobertacchi** [comment]
Helen:
- [ ] add url to search field
- [ ] move search field to URL
- [ ] Tree Listing Page: order by tree, branch, date

**Comment by joaobertacchi** [comment]
Comments from @padovan:
Tree Listing Page
- [ ] remove Tree URL column and turn it into hoover
- [ ] date columns: add time in a hover

Build Status
- Success
- Failed
- Inconclusive (Unknown)

Boots/Test Status
- Success (PASS)
- Failed (FAIL)
- Inconclusive (ERROR, MISS, SKIP, DONE)



- Add datetime (on hover) on the history graph
- git describe seems to be missing on the per build pages, not sure if that's just the data not going into the database or not.
- tree view: commit/tag should be wider
- tree view:  Build status should be pass/fail, not valid/invalid.
- tree view: git url could be trimmed
- history graph: Success/fail instead of valid/invalid

**Comment by joaobertacchi** [comment]
It seems execution list does not filter by current commit

**Comment by joaobertacchi** [comment]
Improve grouping of builds/boots/tests and navigation. @padovan , I think we need extra info to be able to work on that.

**Comment by joaobertacchi** [comment]
Add platform data to Test Details Page (from misc field, works only for maestro)

**Comment by joaobertacchi** [comment]
Show last time a test passed (in Test Details Page). We need more info here. For a specific build? @padovan

**Comment by joaobertacchi** [comment]
Add a build link in the Test Details Page.

**Comment by joaobertacchi** [comment]
Add pagination to the Tree Listing Page url

**Comment by joaobertacchi** [comment]
On Tree Listing Page, navigate to Builds/Boots/Tests tab depending on where the user clicked.

**Comment by joaobertacchi** [comment]
Filters does not affect the History Chart, but it should.

**Comment by joaobertacchi** [comment]
Add "under development" message to Tree Listing Page (p0)

**Comment by joaobertacchi** [comment]
Right-click to open in a new window/tab.
