### ISSUE TITLE
Epic 3: Tree Details Page with functional Boots tab

### ISSUE THREAD

**Issue by bdilly** [kernelci/dashboard#5]
**Sprint Goal**: navigate to any Tree Details pages in Tree Listing page (the client will pick one during demo). In Builds tab, User expands the builds accordion and clicks the Build logs link, that opens it in a different tab. User clicks the Show More link for that same build and navigates to the selected Build Details Page. From there user clicks Kernel config link, that opens it in a different tab.
User navigates to Boots tab. User will do some filtering in the Boots tab. Filtering must affect all the displayed components. User clears the filters.

Details:
- tabs in Tree Details pages: use the following order Builds, Boots, Tests. The Builds tab is opened right away. Navigation to and from Builds and Boots tabs must work. Tests tab is greyed out.
- Builds Listing Component: when the accordion expands, a Show More link is available in the bottom of the item. It navigates to the Build Details Page.
- Build Logs link navigate to the logs instead of showing Logs Component.

Components to build:
- Build Details Page
- Filter Page (for Boots)

To Design:
- how to navigate back to Trees Listing Page? (breadcrumbs? update designs)

Acceptance Criteria:
- App must be deployed to Azure
- Tree Listing Page showing all trees (not using a pre-configured list)
- Tree Listing Page identifies tree HEAD automatically (requires coordination with kernelci team to accomplish it)
- Pick latest commit from kcidb for a particular tree/branch (requires coordination with kernelci team to accomplish it)
- All links in Build Details Page must function (if data is still available)
- We won't show the Regressions Chart

Tasks
- [ ] Build Details Page (5)
- [ ] Tree Details Page (Boots tab integration, navigation, state mgmt, data fetch, etc) (8)
- [ ] Deploy to the Cloud (5)
