### ISSUE TITLE
Epic 12

### ISSUE THREAD

**Issue by joaobertacchi** [kernelci/dashboard#583]
- **General**
    - [ ] #596 [BLOCKED (NEED DISCUSSION)]
    - [x] #597
    - Log Details Page
      - [x] #595
      - [x] #594
    - Tree/Hardware Details Page
      - [x] #593
      - [ ] #592 [BLOCKED BY 591][NEXT SPRINT]
      - [ ] #584 [BLOCKED BY KERNEL CI]
      - Build Execution List
        - [x] #590
      - Chart Card
        - [x] #589
    - [ ] #591 [NEXT SPRINT]
- **Hardware Monitor**
    - Hardware Listing Page
        - Hardware Details Page
            - [x] #447
            - [x] #477 
            - [ ] #588 [NEXT SPRINT]
            - [x] #585
            - [x] #582 
            - [x] #586 

- **URL**
    - [x] #396 

- **Custom Monitor**
    - [ ] #637
    - [ ] #638
    - [ ] #639

- **Bugs**
  - [x] #577 
  - [x] #545 
  - [x] #578 
  - [x] #525 
  - [x] #601 
  - [x] #627 
  - [x] #605 
  - [x] #644
